language: android
android:
  components:
  - build-tools-18.1.1
  - android-19
  - extra
before_script:
- echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- android update project -p .
- cd APP/
script:
- ant emma debug
env:
  global:
    secure: INVZ1COe8NGLKl52BcEErnrnvdtfUKSLLFQXn2hdTSjN0CIUz5ZMQDJkVRi2yaFFYiW9TFXuvyM/m6DDXCb7y5PmA8fe85HJt/9tJlohILFAcMD6y7NCoT8QfgjqYSALyQK7p9KuIKvFymU0wIn6kIOrMzyKUdsa1iAqdqt+S8Q=
after_script:
  - cd ..
  - chmod +x push_javadoc_to_gh_page.sh
  - javadoc -d ./javadoc/ -sourcepath ./APP/src/ -subpackages com
  - ./push_javadoc_to_gh_page.sh
